name: CoreMiner pipeline
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{secrets.SECRET_TOKEN}}
    - name: Bump version
      id: version_bump
      uses: anothrNick/github-tag-action@1.13.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: "patch"
        RELEASE_BRANCHES: "master"
        WITH_V: true
    - name: docker login
      run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.SECRET_TOKEN }}
    - name: docker build
      run: docker build . -t ghcr.io/catchthatrabbit/ethminer/coreminer:${{steps.version_bump.outputs.tag}} -t ghcr.io/catchthatrabbit/ethminer/coreminer:latest
    - name: docker push
      run: docker push --all-tags ghcr.io/catchthatrabbit/ethminer/coreminer
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{secrets.CORE_TOKEN}}
    - name: Build
      run: |
        mkdir build && cd build
        cmake ..
        make all
