name: CoreMiner pipeline
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{secrets.GITHUB_TOKEN}}
    - name: Version
      id: version_bump
      uses: anothrNick/github-tag-action@1.13.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: "patch"
        RELEASE_BRANCHES: "master"
        WITH_V: true
    - name: Docker
      run: |
        docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.SECRET_TOKEN }}
        docker build . -t ghcr.io/catchthatrabbit/ethminer/coreminer:${{steps.version_bump.outputs.tag}} -t ghcr.io/catchthatrabbit/ethminer/coreminer:latest
        docker push --all-tags ghcr.io/catchthatrabbit/ethminer/coreminer
    - name: Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version_bump.outputs.tag }}
        release_name: miner ${{ steps.version_bump.outputs.tag }}
        draft: false
        prerelease: false
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{secrets.GITHUB_TOKEN}}
    - name: Build
      run: |
        mkdir build && cd build
        cmake ..
        make all
